export enum InterventionsSupportPlan {
	ACADEMIC_AREA = 'ACADEMIC_AREA',
	SOCIOEMOTIONAL_AREA = 'SOCIOEMOTIONAL_AREA',
	COMMUNICATION_AREA = 'COMMUNICATION_AREA',
	AREA_AUTONOMY = 'AREA_AUTONOMY',
	MOTOR_AREA = 'MOTOR_AREA',
	SENSORY_AREA = 'SENSORY_AREA',
	COGNITIVE_AREA = 'COGNITIVE_AREA',
	CURRICULAR_AREA = 'CURRICULAR_AREA',
}
