export enum CriteriaStrategiesSupportPlan {
	PRESENTATION_AND_REPRESENTATION = 'PRESENTATION_AND_REPRESENTATION',
	EXECUTION_AND_EXPRESSION = 'EXECUTION_AND_EXPRESSION',
}

export enum StrategySupportPlan {
	PERCEPTION_OF_INFORMATION = 'PERCEPTION_OF_INFORMATION',
	REPRESENTATION_OF_INFORMATION = 'REPRESENTATION_OF_INFORMATION',
	UNDERSTANDING_THE_INFORMATION = 'UNDERSTANDING_THE_INFORMATION',
	EXPRESSION_AND_FLUENCY = 'EXPRESSION_AND_FLUENCY',
	PHYSICAL_ACTION = 'PHYSICAL_ACTION',
}
